baseURL = "http://1612628.github.io/"
languageCode = "en-us"
title = "Duy-Thanh Blog"
author = "Duy-Thanh Nguyen"
theme = "hugo-dgraph-theme"

# Number of blogs you want to list on a single page.
paginate = 5
paginatePath  ="page"

[params]
  googleAnalytics = ""

  # To integrate discourse commenting system and also to display discourse in the footer.
  discourse = ""

  # The path of the repo excluding https://github.com. This would work only for public repos. It is used for displaying stars for the repo.
  github = "1612628/My_Blog_HuGo"

  # Website url, used to have a link in the footer as well as on the top.
  website = "https://1612628.github.io"

  # Twitter handle for sharing the post via
  twitter = ""

  # Website demo url, used on the top.
  demo = "https://1612628.github.io"

  # Wiki url, used to have a link in the footer.
  
  # Slack url, used to have a link in the footer.
  
  # Angel list startup profile name, used to have a link in the footer.

copyright = "Copyright (c) 2019 - 2026, Duy-Thanh Nguyen; all rights reserved."